---
title: "Data Interview"
date: "06/02/2022"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
knit: (function(i, encoding) {apstyle::render(i, encoding)})
---
<!-- Timestamp: leave this in to automatically track when a file is rendered -->
*Rendered at `r format(Sys.time(), '%I:%M %p, %b. %d, %Y')`*

<!-- Contact info: leave author/reporter/editor contact info here -->
*Firstname Lastname (<email@domain.com>)*

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
  )

knitr::opts_knit$set(
  root.dir = rprojroot::find_rstudio_root_file()
  )
```

```{r initialize}
# Load files, environment variables, libraries, etc. here
library(tidyverse)
library(ggplot2)
library(apstyle)
library(rvest)
library(httr)

charlotte_picks <- read_csv("./data/source/charlottepicks_bbref.csv")
nola_picks <- read_csv("./data/source/nolapicks_bbref.csv")
kidd_gilchrist <- read_csv("./data/source/mkg.csv")
davis <- read_csv("./data/source/anthonydavis.csv")
charlotte_seasons <- read_csv("./data/source/charlotte_seasons.csv")
nola_seasons <- read_csv("./data/source/nola_seasons.csv")
```

```{r}
charlotte_picks <-
charlotte_picks[!grepl("\\(", charlotte_picks$Player), -1] %>%
  select(-c("MP...9", "PTS...10", "TRB...11", "AST...12")) %>%
  rename(
    MPG = MP...16,
    PPG = PTS...17,
    RPG = TRB...18,
    APG = AST...19
  )

head(charlotte_picks)
```

```{r}
charlotte_picks %>%
  group_by(Year) %>%
  summarize(picks = n())
```

```{r}
charlotte_picks %>%
  group_by(College) %>%
  summarize(picks = n()) %>%
  arrange(desc(picks))
```

```{r}
charlotte_picks %>%
  arrange(desc(PPG))
```

```{r}
nola_picks <-
nola_picks[!grepl("\\(", nola_picks$Player), -1] %>%
  select(-c("MP...9", "PTS...10", "TRB...11", "AST...12")) %>%
  rename(
    MPG = MP...16,
    PPG = PTS...17,
    RPG = TRB...18,
    APG = AST...19
  )

head(nola_picks)
```

```{r}
nola_picks %>%
  arrange(desc(PPG))
```

```{r}
charlotte_picks %>%
  arrange(desc(VORP))
```

```{r}
nola_picks %>%
  arrange(desc(VORP))
```

```{r}
charlotte_lottery <-
GET("https://basketball.realgm.com/nba/teams/Charlotte-Hornets/3/Lottery-History") %>%
  content(as = "text") %>%
  read_html() %>%
  html_elements('table') %>%
  .[[3]] %>%
  html_table() %>%
  filter(Year >= 2005) %>%
  rename('PreLottery' = 'Pre-Lottery Position',
         'Change' = 'Pick Change') %>%
  mutate(PreLottery = as.numeric(str_sub(PreLottery, end=-3)),
         PreLottery2 = ifelse(Change==0, NA, PreLottery),
         fill_color = ifelse(PreLottery2>Pick, "green", "red"),
         line_stop = ifelse(PreLottery2>Pick, PreLottery2-0.3, PreLottery2+0.3)) %>%
  select("Year", "Odds", "PreLottery", "Pick", "Change", "PreLottery2", "fill_color", "line_stop")

charlotte_lottery
```

```{r}
ggplot(charlotte_lottery) +
  geom_segment(aes(x = Year, xend = Year, y = Pick, yend = line_stop),
               linetype="dashed",
                color = "darkgrey",
               opacity=0.1) +
  geom_point(aes(x=Year, y=Pick, size=3),
             shape=21,
             stroke=1.2,
             fill="#00788C",
             color="#1D1160") +
  geom_point(aes(x=Year, y=PreLottery2, size=3, alpha=0.5),
             shape=21,
             stroke=1.2,
             fill=charlotte_lottery$fill_color,
             color="darkgrey") +
  scale_x_continuous(
    limits = c(2005, 2023),
    breaks = seq(2005, 2023, 1),
    name = NULL
  ) +
  scale_y_reverse(
    limits = c(14, 1),
    breaks = seq(14:1),
    name = "Pick"
  ) +
  labs(
    title = "Charlotte's Draft History",
    subtitle = "Pre-Lottery Position versus Actual Pick",
    caption = "Source: RealGM"
  ) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, vjust=0.5),
        legend.position = "none",
        plot.title = element_text(face = "bold", size = 18),
        plot.subtitle = element_text(size = 12),
        plot.caption = element_text(color="darkgrey", hjust=0, vjust=0.5))
```

```{r}
charlotte_seasons <-
charlotte_seasons %>%
  rename('WinPercent' = 'W/L%') %>%
  select("Season", "Team", "W", "L", "WinPercent")
```


```{r}
ggplot(charlotte_seasons) +
  geom_segment(aes(x = -Inf, xend = Inf, y = 0.5, yend = 0.5),
               linetype="dashed",
                color = "darkgrey") +
  geom_col(aes(x=Season, y=WinPercent),
           fill="#00788C",
           color="#1D1160") +
  scale_y_continuous(
    limits = c(0, 1),
    breaks = seq(0, 1, .1),
    name = "Winning Percentage") +
  labs(
    title = "Charlotte's Not-so-Winning Tradition",
    subtitle = "The Bobcats/Hornets have had very few winning seasons since 2005",
    caption = "Source: basketball-reference.com") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, vjust=0.5),
        axis.title.x = element_blank(),
        plot.title = element_text(face = "bold", size = 18),
        plot.subtitle = element_text(size = 12),
        plot.caption = element_text(color="darkgrey", hjust=0, vjust=0.5))
```

```{r}
davis <-
davis %>%
  mutate(WARP = VORP * 2.7,
         SeasonNum = as.numeric(str_sub(Season, end=-4)),
         Name = "Anthony Davis") %>%
  select("Name", "Season", "WARP", "SeasonNum")

kidd_gilchrist <-
kidd_gilchrist %>%
  mutate(WARP = VORP * 2.7,
         SeasonNum = as.numeric(str_sub(Season, end=-4)),
         Name = "Michael Kidd-Gilchrist") %>%
  select("Name", "Season", "WARP", "SeasonNum")

davis_mkg_points <- rbind(davis, kidd_gilchrist)
```

```{r}
ggplot() +
  geom_segment(aes(x = -Inf, xend = Inf, y = 0, yend = 0),
               linetype="dashed",
                color = "black") +
  geom_line(data=davis,
            aes(x=SeasonNum, y=WARP),
            color="gold2",
            size=1.1) +
  geom_line(data=kidd_gilchrist,
            aes(x=SeasonNum, y=WARP),
            color="#00788C",
            size=1.1) +
  geom_point(data=davis_mkg_points,
             aes(x=SeasonNum, y=WARP, color=Name)) +
  scale_color_manual(values = c("gold2", "#00788C"),
                    labels = c("Davis", "Kidd-Gilchrist"),
                    name = "Player") +
  scale_x_continuous(breaks = davis$SeasonNum,
                     labels = davis$Season) +
  scale_y_continuous(limits = c(-5, 20),
                     breaks = seq(-5, 20, 5),
                     name = "Wins Over Replacement") +
  labs(
    title = "The Anthony Davis / Michael Kidd-Gilchrist Fiasco",
    subtitle = "Davis became a much more valuable player than his former college teammate.",
    caption = "Source: basketball-reference.com") +
  theme_classic() +
  theme(axis.text.x = element_text(vjust=0.5),
        axis.title.x = element_blank(),
        plot.title = element_text(face = "bold", size = 18),
        plot.subtitle = element_text(size = 12),
        plot.caption = element_text(color="darkgrey", hjust=0, vjust=0.5))
  
```

```{r}
paul <-
  read_csv("./data/source/paul.csv") %>%
  mutate(WARP = VORP * 2.7,
         SeasonNum = as.numeric(str_sub(Season, end=-4)),
         Name = "Chris Paul") %>%
  select("Name", "Season", "WARP", "SeasonNum")

felton <-
  read_csv("./data/source/felton.csv") %>%
  mutate(WARP = VORP * 2.7,
         SeasonNum = as.numeric(str_sub(Season, end=-4)),
         Name = "Raymond Felton") %>%
  select("Name", "Season", "WARP", "SeasonNum")

paul_cp3_points <- rbind(paul, felton)
```

```{r}
ggplot() +
  geom_segment(aes(x = -Inf, xend = Inf, y = 0, yend = 0),
               linetype="dashed",
                color = "black") +
  geom_line(data=paul,
            aes(x=SeasonNum, y=WARP),
            color="#1D8CAB",
            size=1.1) +
  geom_line(data=felton,
            aes(x=SeasonNum, y=WARP),
            color="#fb5b13",
            size=1.1) +
  geom_point(data=paul_cp3_points,
             aes(x=SeasonNum, y=WARP, color=Name)) +
  scale_color_manual(values = c("#1D8CAB", "#fb5b13"),
                    labels = c("Paul", "Felton"),
                    name = "Player") +
  scale_x_continuous(breaks = paul$SeasonNum,
                     labels = paul$Season) +
  scale_y_continuous(limits = c(-3, 27),
                     breaks = seq(-3, 27, 5),
                     name = "Wins Over Replacement") +
  labs(
    title = "The One That Got Away",
    subtitle = "Wake Forest star Chris Paul made an instant impact in New Orleans",
    caption = "Source: basketball-reference.com") +
  theme_classic() +
  theme(axis.text.x = element_text(vjust=0.5),
        axis.title.x = element_blank(),
        plot.title = element_text(face = "bold", size = 18),
        plot.subtitle = element_text(size = 12),
        plot.caption = element_text(color="darkgrey", hjust=0, vjust=0.5))

```


<!-- This section is for a tests code block -->

```{r tests}
# Leave this block of code at the end of the file
# If a test fails it will stop the Rmd document from knitting
# Run tests like so:
# source("tests/etl_test.R")
```
